<?php

/**
 * @file
 */

use Drupal\block\BlockInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_block_access().
 */
function pcc_news_header_block_access(BlockInterface $block, $operation, AccountInterface $account) {
  if ($operation === 'view' && $block->getPluginId() === 'localgov_page_header_block') {
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node instanceof NodeInterface && $node->bundle() === 'localgov_news_article') {
      return AccessResult::allowed()->addCacheContexts(['route']);
    }
  }
  return AccessResult::neutral();
}

/**
 * Implements hook_preprocess_block().
 */
function pcc_news_header_preprocess_block(&$variables) {
  if ($variables['plugin_id'] === 'localgov_page_header_block') {
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node instanceof NodeInterface && $node->bundle() === 'localgov_news_article') {
      $variables['content'][0]['#subtitle'] = NULL;
      $variables['content'][0]['#lede'] = NULL;
    }
  }
}
